# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/tecno/mt6789-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter LG7n LG8n,$(TARGET_DEVICE)),)

endif
