#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/tecno/mt6789-common

PRODUCT_COPY_FILES += \
    vendor/tecno/mt6789-common/proprietary/vendor/data/camera/vidhance/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/data/camera/vidhance/vidhance_calibration \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/anc_siq/cache_s5kjn1_17201715_back_g97:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/cache_s5kjn1_17201715_back_g97 \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/anc_siq/dgain_mask_s5kjn1_17201715_back_g97.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/dgain_mask_s5kjn1_17201715_back_g97.bin \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/anc_siq/siq_ocl_cache_s5kjn1_17201715_back_g97:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_ocl_cache_s5kjn1_17201715_back_g97 \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/anc_siq/siq_params_s5kjn1_17201715_back_g97.bin:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/siq_params_s5kjn1_17201715_back_g97.bin \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/anc_siq/superiq_model_s5kjn1_17201715_back_g97:$(TARGET_COPY_OUT_VENDOR)/etc/anc_siq/superiq_model_s5kjn1_17201715_back_g97 \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/apdb/APDB_MT6789___W2227:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6789___W2227 \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/apdb/APDB_MT6789___W2227_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6789___W2227_ENUM \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/cam3atms_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cam3atms_profiles.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/fsfp-config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/fsfp-config.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.trustonic.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.bip_ap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip_ap.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.gps_pwr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_pwr.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.nxp.nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nxp.nfc.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.otg.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.otg.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.thermal_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_core.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/trustonic.mc_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.mc_kmsetkey_ca.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.fptool.fingerprint@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.fptool.fingerprint@2.0-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/meow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/meow.cfg \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/tran_camprofiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/tran_camprofiles.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/tecno/mt6789-common/proprietary/vendor/etc/wfd_source_capability.csv:$(TARGET_COPY_OUT_VENDOR)/etc/wfd_source_capability.csv \
    vendor/tecno/mt6789-common/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libAVCSecureVencCA \
    libadpcmdec_mtk \
    libaedv \
    libbwc \
    libccci_util \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libmp3dec_mtk \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libverno \
    libwo \
    arm.graphics-V1-ndk_platform \
    libmtk_drvb \
    vendor.mediatek.hardware.videotelephony@1.0 \
    libHEVCdec_sa.ca7.android \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    librcs_interface \
    librcs_volte_core \
    libthha \
    libvcodec_utility_plat.mt6789 \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvcodec_utility \
    libvcodec_utility_v3a \
    libvcodecdrv \
    libvcodecdrv_v3a \
    libvpudv3a_vcodec \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    android.hardware.bluetooth@1.1-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.sensors@2.X-subhal-mediatek \
    audio.primary.mediatek \
    audio.r_submix.mediatek \
    fsfingerprint.default \
    gps.default \
    hwcomposer.mtk_common \
    kmsetkey.trustonic \
    libMcGatekeeper \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mediatek.V2.0 \
    sound_trigger.primary.mt6789 \
    vendor.fptool.fingerprint@2.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    lbs_hidl_service-impl \
    lib3a.ae.pipe \
    libBasicModule \
    libCamera_gc08a3mipiraw_Default_Capture \
    libCamera_gc08a3mipiraw_Default_Preview \
    libCamera_gc08a3mipiraw_Default_Video \
    libCamera_gc08a3mipiraw_Face_Beauty \
    libCamera_gc08a3mipiraw_Face_Beauty_Preview \
    libCamera_gc08a3mipiraw_Face_Beauty_mfll \
    libCamera_gc08a3mipiraw_LLHDR_0EV \
    libCamera_gc08a3mipiraw_NHDR_0EV \
    libCamera_gc08a3mipiraw_Panorama \
    libCamera_gc08a3mipiraw_Portrait \
    libCamera_gc08a3mipiraw_Portrait_Preview \
    libCamera_gc08a3mipiraw_ThirdAPP_Capture \
    libCamera_gc08a3mipiraw_ThirdAPP_Preview \
    libCamera_gc08a3mipiraw_Video_720 \
    libCamera_gc08a3mipiraw_Zoom_Preview \
    libCamera_gc08a3mipiraw_short_video \
    libCamera_pblcgc08a3mipiraw_Default_Capture \
    libCamera_pblcgc08a3mipiraw_Default_Preview \
    libCamera_pblcgc08a3mipiraw_Default_Video \
    libCamera_pblcgc08a3mipiraw_Face_Beauty \
    libCamera_pblcgc08a3mipiraw_Face_Beauty_Preview \
    libCamera_pblcgc08a3mipiraw_Face_Beauty_mfll \
    libCamera_pblcgc08a3mipiraw_LLHDR_0EV \
    libCamera_pblcgc08a3mipiraw_NHDR_0EV \
    libCamera_pblcgc08a3mipiraw_Panorama \
    libCamera_pblcgc08a3mipiraw_Portrait \
    libCamera_pblcgc08a3mipiraw_Portrait_Preview \
    libCamera_pblcgc08a3mipiraw_ThirdAPP_Capture \
    libCamera_pblcgc08a3mipiraw_ThirdAPP_Preview \
    libCamera_pblcgc08a3mipiraw_Video_720 \
    libCamera_pblcgc08a3mipiraw_Zoom_Preview \
    libCamera_pblcgc08a3mipiraw_short_video \
    libCamera_pblcs5kjn1mipiraw_Boken_Capture \
    libCamera_pblcs5kjn1mipiraw_Capture_Zoom1 \
    libCamera_pblcs5kjn1mipiraw_Capture_Zoom2 \
    libCamera_pblcs5kjn1mipiraw_Default_Capture \
    libCamera_pblcs5kjn1mipiraw_Default_Preview \
    libCamera_pblcs5kjn1mipiraw_Default_Video \
    libCamera_pblcs5kjn1mipiraw_Documents_Capture \
    libCamera_pblcs5kjn1mipiraw_FaceBeauty \
    libCamera_pblcs5kjn1mipiraw_FaceBeauty_mfll \
    libCamera_pblcs5kjn1mipiraw_HDR_MINUS_EV \
    libCamera_pblcs5kjn1mipiraw_LLHDR_0EV \
    libCamera_pblcs5kjn1mipiraw_NHDR_0EV \
    libCamera_pblcs5kjn1mipiraw_Panorama \
    libCamera_pblcs5kjn1mipiraw_Preview_Zoom1 \
    libCamera_pblcs5kjn1mipiraw_Preview_Zoom2 \
    libCamera_pblcs5kjn1mipiraw_Pro_Capture \
    libCamera_pblcs5kjn1mipiraw_Pro_Preview \
    libCamera_pblcs5kjn1mipiraw_Resolution \
    libCamera_pblcs5kjn1mipiraw_Resolution_FaceCapture \
    libCamera_pblcs5kjn1mipiraw_Resolution_Hiso_zoom1 \
    libCamera_pblcs5kjn1mipiraw_Resolution_Hiso_zoom2 \
    libCamera_pblcs5kjn1mipiraw_Resolution_SceneCapture \
    libCamera_pblcs5kjn1mipiraw_Resolution_preview \
    libCamera_pblcs5kjn1mipiraw_Resolution_zoom \
    libCamera_pblcs5kjn1mipiraw_Scene_Capture_4cell_zoom1 \
    libCamera_pblcs5kjn1mipiraw_Scene_Capture_4cell_zoom2 \
    libCamera_pblcs5kjn1mipiraw_ShortVideo \
    libCamera_pblcs5kjn1mipiraw_SuperNight \
    libCamera_pblcs5kjn1mipiraw_ThirdAPP_Capture \
    libCamera_pblcs5kjn1mipiraw_ThirdAPP_Preview \
    libCamera_pblcs5kjn1mipiraw_Video_1080P \
    libCamera_pblcs5kjn1mipiraw_Video_120fps \
    libCamera_pblcs5kjn1mipiraw_Video_240fps \
    libCamera_pblcs5kjn1mipiraw_Video_2K \
    libCamera_pblcs5kjn1mipiraw_Video_60fps \
    libCamera_pblcs5kjn1mipiraw_Video_720P \
    libCamera_pblcs5kjn1mipiraw_Video_EIS \
    libCamera_pblcs5kjn1mipiraw_Video_Zoom1 \
    libCamera_pblcs5kjn1mipiraw_Video_Zoom2 \
    libCamera_pbrogc08a3mipiraw_360HDR \
    libCamera_pbrogc08a3mipiraw_3rd_Capture \
    libCamera_pbrogc08a3mipiraw_3rd_Capture_FD \
    libCamera_pbrogc08a3mipiraw_3rd_Preview \
    libCamera_pbrogc08a3mipiraw_3rd_Preview_FD \
    libCamera_pbrogc08a3mipiraw_Boken_Capture \
    libCamera_pbrogc08a3mipiraw_Capture_Zoom1 \
    libCamera_pbrogc08a3mipiraw_Capture_Zoom2 \
    libCamera_pbrogc08a3mipiraw_FaceBeauty \
    libCamera_pbrogc08a3mipiraw_HDR_MINUS_EV \
    libCamera_pbrogc08a3mipiraw_NHDR_0EV \
    libCamera_pbrogc08a3mipiraw_Preview_Zoom1 \
    libCamera_pbrogc08a3mipiraw_Preview_Zoom2 \
    libCamera_pbrogc08a3mipiraw_Resolution \
    libCamera_pbrogc08a3mipiraw_Resolution_Preview \
    libCamera_pbrogc08a3mipiraw_Resolution_zoom \
    libCamera_pbrogc08a3mipiraw_Scene_EIS_Video \
    libCamera_pbrogc08a3mipiraw_ShortVideo \
    libCamera_pbrogc08a3mipiraw_SuperNight \
    libCamera_pbrogc08a3mipiraw_Video_2k \
    libCamera_pbrogc08a3mipiraw_Video_720 \
    libCamera_pbros5kjn1mipiraw_360HDR \
    libCamera_pbros5kjn1mipiraw_3rd_Capture \
    libCamera_pbros5kjn1mipiraw_3rd_Capture_FD \
    libCamera_pbros5kjn1mipiraw_3rd_Preview \
    libCamera_pbros5kjn1mipiraw_3rd_Preview_FD \
    libCamera_pbros5kjn1mipiraw_Boken_Capture \
    libCamera_pbros5kjn1mipiraw_Capture_Zoom1 \
    libCamera_pbros5kjn1mipiraw_Capture_Zoom2 \
    libCamera_pbros5kjn1mipiraw_NHDR_0EV \
    libCamera_pbros5kjn1mipiraw_Preview_Zoom1 \
    libCamera_pbros5kjn1mipiraw_Preview_Zoom2 \
    libCamera_pbros5kjn1mipiraw_Pro_scene \
    libCamera_pbros5kjn1mipiraw_Resolution \
    libCamera_pbros5kjn1mipiraw_Resolution_zoom \
    libCamera_pbros5kjn1mipiraw_Scene_Capture_Remosaic \
    libCamera_pbros5kjn1mipiraw_Scene_PreFlash_Preview \
    libCamera_pbros5kjn1mipiraw_SuperNight \
    libCamera_pbros5kjn1mipiraw_Video \
    libCamera_pbros5kjn1mipiraw_Video_1080p \
    libCamera_pbros5kjn1mipiraw_Video_120fps \
    libCamera_pbros5kjn1mipiraw_Video_240fps \
    libCamera_pbros5kjn1mipiraw_Video_2k \
    libCamera_pbros5kjn1mipiraw_Video_EIS \
    libCamera_pbros5kjn1mipiraw_Video_Zoom1 \
    libCamera_pbros5kjn1mipiraw_Video_Zoom2 \
    libCamera_s5kjn1mipiraw_Boken_Capture \
    libCamera_s5kjn1mipiraw_Capture_Zoom1 \
    libCamera_s5kjn1mipiraw_Capture_Zoom2 \
    libCamera_s5kjn1mipiraw_Default_Capture \
    libCamera_s5kjn1mipiraw_Default_Preview \
    libCamera_s5kjn1mipiraw_Default_Video \
    libCamera_s5kjn1mipiraw_Documents_Capture \
    libCamera_s5kjn1mipiraw_FaceBeauty \
    libCamera_s5kjn1mipiraw_FaceBeauty_mfll \
    libCamera_s5kjn1mipiraw_HDR_MINUS_EV \
    libCamera_s5kjn1mipiraw_LLHDR_0EV \
    libCamera_s5kjn1mipiraw_NHDR_0EV \
    libCamera_s5kjn1mipiraw_Panorama \
    libCamera_s5kjn1mipiraw_Preview_Zoom1 \
    libCamera_s5kjn1mipiraw_Preview_Zoom2 \
    libCamera_s5kjn1mipiraw_Pro_Capture \
    libCamera_s5kjn1mipiraw_Pro_Preview \
    libCamera_s5kjn1mipiraw_Resolution \
    libCamera_s5kjn1mipiraw_Resolution_FaceCapture \
    libCamera_s5kjn1mipiraw_Resolution_Hiso_zoom1 \
    libCamera_s5kjn1mipiraw_Resolution_Hiso_zoom2 \
    libCamera_s5kjn1mipiraw_Resolution_SceneCapture \
    libCamera_s5kjn1mipiraw_Resolution_preview \
    libCamera_s5kjn1mipiraw_Resolution_zoom \
    libCamera_s5kjn1mipiraw_Scene_Capture_4cell_zoom1 \
    libCamera_s5kjn1mipiraw_Scene_Capture_4cell_zoom2 \
    libCamera_s5kjn1mipiraw_ShortVideo \
    libCamera_s5kjn1mipiraw_SuperNight \
    libCamera_s5kjn1mipiraw_ThirdAPP_Capture \
    libCamera_s5kjn1mipiraw_ThirdAPP_Preview \
    libCamera_s5kjn1mipiraw_Video_1080P \
    libCamera_s5kjn1mipiraw_Video_120fps \
    libCamera_s5kjn1mipiraw_Video_240fps \
    libCamera_s5kjn1mipiraw_Video_2K \
    libCamera_s5kjn1mipiraw_Video_60fps \
    libCamera_s5kjn1mipiraw_Video_720P \
    libCamera_s5kjn1mipiraw_Video_EIS \
    libCamera_s5kjn1mipiraw_Video_Zoom1 \
    libCamera_s5kjn1mipiraw_Video_Zoom2 \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libMcClient \
    libMegviiHum \
    libMtkSpeechEnh \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libTEECommon \
    libVkLayer_mtk_rt_sdk \
    lib_iir \
    lib_speech_enh \
    libaal_key \
    libaal_mtk \
    libalsautils-v32 \
    libanc_hdr \
    libanc_hdr_adapter_s5kjn1_17201715_back_g97 \
    libancbase \
    libancbase_848 \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_hw_test \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libc++_shared \
    libcam.seninfn3d \
    libcam3_tranelapsedtime \
    libcam3_tranpriorityctrl \
    libcam3_transerverengine \
    libcamalgo.3dnr \
    libcamalgo.WarpMapResizer \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.hdr10p \
    libcamalgo.lmv \
    libcamalgo.mcnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.vsdofUtil \
    libcamalgo.warp \
    libcares_naptr \
    libcarrierconfig \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_mtk_alacdec \
    libcodec2_soft_mtk_apedec \
    libcodec2_soft_mtk_imaadpcmdec \
    libcodec2_soft_mtk_mp3dec \
    libcodec2_soft_mtk_msadpcmdec \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libdecrypt \
    libdre \
    libdynamiclog \
    libfeaturepolicy \
    libfgauge_gm30 \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgwsd-ril \
    libgwsdv2-ril \
    libgwsdv3-ril \
    libhdrvideo \
    libheichal \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimgsensorca \
    libimsg_log \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    libmegface \
    libminiui \
    libmipc \
    libmmagent \
    libmml \
    libmmprofile \
    libmnetlink_v104 \
    libmsbc_mtk \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam_fdWarpConvert \
    libmtkcam_pipelinepolicy-aov \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkisp_metadata_v2 \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuron_graph_delegate.mtk \
    libnir_neon_driver_ndk.mtk.vndk \
    libnnp \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboemcrypto \
    libpixelflinger \
    libpn557_fw \
    libpower_timer \
    libpqframework \
    libratconfig \
    librgbwlightsensor \
    librilfusion \
    librpc \
    librt_extamp_intf \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstorage_otp \
    libsysenv \
    libtflite_mtk \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvidhance \
    libvidhance_active_ois \
    libvidhance_stabilizer \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvpu \
    libvpu5 \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    fake_serial_yuv_IdxMgr \
    fake_serial_yuv_tuning \
    gc08a3_mipi_raw_IdxMgr \
    gc08a3_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_fakeserialyuv_E2EHDR_Preview \
    libCamera_fakeserialyuv_E2EHDR_Video \
    libCamera_fakeserialyuv_Face_Capture \
    libCamera_fakeserialyuv_Flash_Capture \
    libCamera_fakeserialyuv_HDR_Capture \
    libCamera_fakeserialyuv_HDR_Preview \
    libCamera_fakeserialyuv_HDR_Reconfig_Preview \
    libCamera_fakeserialyuv_HDR_Reconfig_Video \
    libCamera_fakeserialyuv_HDR_Video \
    libCamera_fakeserialyuv_N3D_Capture \
    libCamera_fakeserialyuv_N3D_Preview \
    libCamera_fakeserialyuv_N3D_Video \
    libCamera_fakeserialyuv_P1_YUV \
    libCamera_fakeserialyuv_Scene_Capture \
    libCamera_fakeserialyuv_Scene_Capture_4cell \
    libCamera_fakeserialyuv_Scene_Preview \
    libCamera_fakeserialyuv_Scene_Preview_4k \
    libCamera_fakeserialyuv_Scene_Preview_ZSD_Flash \
    libCamera_fakeserialyuv_Video_1080 \
    libCamera_fakeserialyuv_Video_4k \
    libCamera_gc08a3mipiraw_E2EHDR_Preview \
    libCamera_gc08a3mipiraw_E2EHDR_Video \
    libCamera_gc08a3mipiraw_Face_Capture \
    libCamera_gc08a3mipiraw_Flash_Capture \
    libCamera_gc08a3mipiraw_HDR_Capture \
    libCamera_gc08a3mipiraw_HDR_Preview \
    libCamera_gc08a3mipiraw_HDR_Reconfig_Preview \
    libCamera_gc08a3mipiraw_HDR_Reconfig_Video \
    libCamera_gc08a3mipiraw_HDR_Video \
    libCamera_gc08a3mipiraw_N3D_Capture \
    libCamera_gc08a3mipiraw_N3D_Preview \
    libCamera_gc08a3mipiraw_N3D_Video \
    libCamera_gc08a3mipiraw_P1_YUV \
    libCamera_gc08a3mipiraw_Scene_Capture \
    libCamera_gc08a3mipiraw_Scene_Capture_4cell \
    libCamera_gc08a3mipiraw_Scene_Preview \
    libCamera_gc08a3mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_gc08a3mipiraw_Video_1080 \
    libCamera_gc08a3mipiraw_Video_4k \
    libCamera_gc08a3mipiraw_Zoom_Capture \
    libCamera_pblcgc08a3mipiraw_E2EHDR_Preview \
    libCamera_pblcgc08a3mipiraw_E2EHDR_Video \
    libCamera_pblcgc08a3mipiraw_Face_Capture \
    libCamera_pblcgc08a3mipiraw_Flash_Capture \
    libCamera_pblcgc08a3mipiraw_HDR_Capture \
    libCamera_pblcgc08a3mipiraw_HDR_Preview \
    libCamera_pblcgc08a3mipiraw_HDR_Reconfig_Preview \
    libCamera_pblcgc08a3mipiraw_HDR_Reconfig_Video \
    libCamera_pblcgc08a3mipiraw_HDR_Video \
    libCamera_pblcgc08a3mipiraw_N3D_Capture \
    libCamera_pblcgc08a3mipiraw_N3D_Preview \
    libCamera_pblcgc08a3mipiraw_N3D_Video \
    libCamera_pblcgc08a3mipiraw_P1_YUV \
    libCamera_pblcgc08a3mipiraw_Scene_Capture \
    libCamera_pblcgc08a3mipiraw_Scene_Capture_4cell \
    libCamera_pblcgc08a3mipiraw_Scene_Preview \
    libCamera_pblcgc08a3mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_pblcgc08a3mipiraw_Video_1080 \
    libCamera_pblcgc08a3mipiraw_Video_4k \
    libCamera_pblcgc08a3mipiraw_Zoom_Capture \
    libCamera_pblcs5kjn1mipiraw_Face_Capture \
    libCamera_pblcs5kjn1mipiraw_Flash_Capture \
    libCamera_pblcs5kjn1mipiraw_Scene_Capture \
    libCamera_pblcs5kjn1mipiraw_Scene_Capture_4cell \
    libCamera_pblcs5kjn1mipiraw_Scene_Preview \
    libCamera_pbrogc08a3mipiraw_Flash_Capture \
    libCamera_pbrogc08a3mipiraw_Scene_Capture \
    libCamera_pbrogc08a3mipiraw_Scene_Capture_4cell \
    libCamera_pbrogc08a3mipiraw_Scene_Preview \
    libCamera_pbrogc08a3mipiraw_Video_1080 \
    libCamera_pbros5kjn1mipiraw_Flash_Capture \
    libCamera_pbros5kjn1mipiraw_Scene_Capture \
    libCamera_pbros5kjn1mipiraw_Scene_Capture_4cell \
    libCamera_pbros5kjn1mipiraw_Scene_Preview \
    libCamera_s5kjn1mipiraw_Face_Capture \
    libCamera_s5kjn1mipiraw_Flash_Capture \
    libCamera_s5kjn1mipiraw_Scene_Capture \
    libCamera_s5kjn1mipiraw_Scene_Capture_4cell \
    libCamera_s5kjn1mipiraw_Scene_Preview \
    libDR \
    libImageEval \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTranASD \
    libTranArcFilter \
    libTranArcFlashNew \
    libTranArcHDR \
    libTranArcLLHDR \
    libTranArcLowLight \
    libTranArcNightHawk \
    libTranBefMakeup \
    libTranDenoise \
    libTranExtImgProc \
    libTranEyeDetect \
    libTranFaceBeauty \
    libTranGenderDetect \
    libTranHumanLight \
    libTranMegHumanEffect \
    libTranPlatHW \
    libTranSTPRRepair \
    libTranSTSingleBlur \
    libTranSlimBody \
    libTranSmartDetection \
    libTranStSuperResolution \
    libTran_Log \
    libTran_mtkPowerAPI \
    libWaterMarkProc \
    lib_sr_indep_ocl \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust_func \
    libaalservice \
    libacdk \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libaiselector \
    libamipengine \
    libarcsoft_beautyshot \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_low_light_shot \
    libarcsoft_night_hawk \
    libarcsoft_torch_portrait_night \
    libcalculatesharpness \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3atms_profiles \
    libcamalgo.ispfeature \
    libcamalgo.lsc \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vsf \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libdenoise \
    libdip_drv \
    libdip_postproc \
    libdpframework \
    libeffect_hal \
    libeffecthal.base \
    libeyedetector \
    libfacesattribute \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libgpudataproducer \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmnl \
    libmpbase \
    libmsnr \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libportrait_repair_ocl \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libremosaic_wrapper \
    libremosaiclib \
    librmsclib1 \
    libsdk_sr \
    libsegmention \
    libsegmentionPre \
    libsmartdetector \
    libst_mobile \
    libst_sr_models \
    libstblur_capture_api \
    libstereoinfoaccessor_vsdof \
    libtf_asd_lib \
    libtflite_native_gainference \
    libtflite_native_inference \
    libtflite_native_seginference \
    libtranssion_beauty \
    libtranssion_bodybeauty \
    libvainr_model \
    pblcgc08a3_mipi_raw_IdxMgr \
    pblcgc08a3_mipi_raw_tuning \
    pblcs5kjn1_mipi_raw_IdxMgr \
    pblcs5kjn1_mipi_raw_tuning \
    pbrogc08a3_mipi_raw_IdxMgr \
    pbrogc08a3_mipi_raw_tuning \
    pbros5kjn1_mipi_raw_IdxMgr \
    pbros5kjn1_mipi_raw_tuning \
    s5kjn1_mipi_raw_IdxMgr \
    s5kjn1_mipi_raw_tuning \
    libmtkcam_streaminfo_plugin-p1stt \
    vendor.fptool.fingerprint@2.0-adapter-helper \
    vendor.fptool.fingerprint@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.transsion.hardware.trancam.trancamserver@1.0 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    GpuGameDriver.mt6789 \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.trustonic.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    lbs_hidl_service@1.0.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    manifest_hwcomposer.xml \
    manifest_media_c2_V1_2_default.xml \
    vendor.transsion.hardware.trancam.trancamserver@1.0.xml \
    autobt \
    bip \
    bip_ap \
    bt_dump \
    ccci_mdinit \
    ccci_rpcd \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.security.keymint-service.trustonic \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6789 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.fptool.fingerprint@2.0-service \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.transsion.hardware.trancam.trancamserver@1.0-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    ipsec_mon \
    kmsetkey_ca.trustonic \
    lbs_hidl_service \
    mcDriverDaemon \
    mnld \
    dumpfaultd.mt6789 \
    jpegtool \
    v3avpud.mt6789 \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    thermal_core \
    volte_clientapi_ua \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_rcs_ua \
    volte_stack \
    volte_ua \
    wlan_assistant \
    wmt_launcher \
    wmt_loader
